version: '3.9'

services:
  zabbix-agent:
    image: zabbix/zabbix-agent:alpine-7.0-latest
    container_name: zabbix-agent
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: zabbix-agent
    restart: always

  postgres:
    image: postgres:15
    container_name: zabbix-postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix"]
      interval: 10s
      timeout: 5s
      retries: 5

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.0-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "10051:10051"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost 10051"]
      interval: 30s
      timeout: 10s
      retries: 3

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.0-latest
    container_name: zabbix-web
    environment:
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix-server
      PHP_TZ: America/Sao_Paulo
    depends_on:
      zabbix-server:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  grafana:
    image: grafana/grafana:10.4.0 #Suporta o plugin do Zabbix
    container_name: grafana
    environment:
      - GF_INSTALL_PLUGINS=alexanderzobnin-zabbix-app
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    depends_on:
      zabbix-web:
        condition: service_healthy

  monitor:
    build: 
      context: ./monitor
      dockerfile: Dockerfile
    container_name: monitor-alertas
    environment:
      TELEGRAM_TOKEN: "SEU_TOKEN"
      TELEGRAM_CHAT_ID: "SEU_CHAT_ID"
      ZABBIX_URL: "http://zabbix-web:8080/api_jsonrpc.php"
      ZABBIX_USER: "Admin"
      ZABBIX_PASSWORD: "zabbix"
      CHECK_INTERVAL: "300"  # 5 minutos entre as verificações
      STARTUP_DELAY: "90"    # Aguarda 90s para testar os serviços novamente
    depends_on:
      zabbix-web:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  grafana-data:
